In [20]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\titan\OneDrive\Desktop\practicedata.csv")

In [3]:
#Display the first 10 rows.

df.head(10)

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,Blinkit,Hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,Blinkit,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
2,10003,C1157,NaN,Chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,NaN,Yes,Yes,4.0,Rider E
3,10004,C1299,BigBasket Now,Mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,NaN,No,No,3.0,Rider D
4,10005,C1262,BigBasket Now,Bengaluru,Household,6,629,503.20,20,19.0,10,8,4025.60,Wallet,Gold,Yes,No,3.0,Rider C
5,10006,C1047,Instamart,Delhi,Personal Care,2,1057,845.60,20,0.0,25,22,4228.00,Wallet,Silver,No,No,1.0,Rider D
6,10007,C1252,Blinkit,Bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
7,10008,C1220,Instamart,Pune,fruit,6,862,689.60,20,59.0,20,19,4827.20,Card,Gold,Yes,Yes,2.0,Rider B
8,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
9,10010,C1053,BigBasket Now,Pune,Snacks,1,843,716.55,15,19.0,25,32,1433.10,Card,Silver,Yes,Yes,3.0,Rider E

In [4]:
#Display the last 10 rows.

df.tail(10)

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
1010,10011,C1077,Blinkit,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
1011,10012,C1238,BigBasket Now,Delhi,Dairy,2,1011,1011.00,0,19.0,10,20,2022.00,COD,NaN,No,No,NaN,Rider B
1012,10013,C1185,Zepto,Pune,Beverages,1,1097,1097.00,0,49.0,15,26,5485.00,UPI,NaN,No,No,2.0,Rider C
1013,10014,C1168,Zepto,Hyderabad,Household,4,496,396.80,20,19.0,30,41,2777.60,Card,Gold,No,No,NaN,Rider A
1014,10015,C1132,Zepto,Pune,Beverages,6,97,67.90,30,39.0,20,30,407.40,COD,Gold,Yes,Yes,2.0,Rider D
1015,10016,C1000,BigBasket Now,Pune,Dairy,2,442,397.80,10,59.0,15,25,795.60,Wallet,NaN,Yes,No,2.0,Rider D
1016,10017,C1205,Blinkit,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,NaN,No,Yes,5.0,Rider E
1017,10018,C1280,Zepto,Chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,NaN,Yes,Yes,3.0,Rider B
1018,10019,C1166,Instamart,NaN,Snacks,3,639,511.20,20,0.0,15,28,3067.20,Wallet,NaN,No,Yes,5.0,Rider B
1019,10020,C1093,Blinkit,Bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [5]:
#no of rows and columns

df.shape #(row,column)

(1020, 19)

In [6]:
#all column names
df.columns

Index(['order_id', 'customer_id', 'platform', 'city', 'category', 'quantity',
       'mrp', 'selling_price', 'discount_percent', 'delivery_fee',
       'promised_time', 'delivery_time', 'order_value', 'payment_mode',
       'membership', 'coupon_used', 'weekend', 'rating', 'delivery_partner'],
      dtype='object')

In [7]:
#Use info() and summarize what you observe.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1020 non-null   int64
 1   customer_id       1020 non-null   object
 2   platform          995 non-null    object
 3   city              994 non-null    object
 4   category          1020 non-null   object
 5   quantity          1020 non-null   int64
 6   mrp               1020 non-null   int64
 7   selling_price     1020 non-null   float64
 8   discount_percent  1020 non-null   int64
 9   delivery_fee      995 non-null    float64
 10  promised_time     1020 non-null   int64
 11  delivery_time     1020 non-null   int64
 12  order_value       1020 non-null   float64
 13  payment_mode      1020 non-null   object
 14  membership        682 non-null    object
 15  coupon_used       1020 non-null   object
 16  weekend           1020 non-null   object
 17  rating            835 non-null    float64
 18  delivery_partner  1020 non-null   object
dtypes: float64(4), int64(6), object(9)
memory usage: 151.5+ KB

In [8]:
df.describe()

,order_id,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,rating
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,995.000000,1020.000000,1020.000000,1020.000000,835.000000
mean,10490.892157,4.453922,619.950000,527.948480,15.127451,31.925628,20.029412,26.214706,2317.001422,2.998802
std,293.939033,2.291520,334.733055,295.886884,10.045697,19.423132,6.955566,9.936204,1847.842166,1.440673
min,10001.000000,1.000000,40.000000,28.700000,0.000000,0.000000,10.000000,5.000000,36.000000,1.000000
25%,10235.750000,2.000000,327.750000,269.025000,5.000000,19.000000,15.000000,19.000000,795.900000,2.000000
50%,10490.500000,4.000000,615.000000,519.650000,15.000000,29.000000,20.000000,26.000000,1849.100000,3.000000
75%,10745.250000,6.250000,915.000000,760.337500,25.000000,49.000000,25.000000,33.000000,3441.562500,4.000000
max,11000.000000,8.000000,1197.000000,1180.000000,30.000000,59.000000,30.000000,48.000000,8976.000000,5.000000

In [9]:
df.memory_usage()

Index                132
order_id            8160
customer_id         8160
platform            8160
city                8160
category            8160
quantity            8160
mrp                 8160
selling_price       8160
discount_percent    8160
delivery_fee        8160
promised_time       8160
delivery_time       8160
order_value         8160
payment_mode        8160
membership          8160
coupon_used         8160
weekend             8160
rating              8160
delivery_partner    8160
dtype: int64

In [10]:
#columns with the most NULL values
df.isnull().sum().idxmax()

'membership'

In [11]:
#How many unique platforms are present before cleaning?

df['platform'].nunique()
df['platform'].unique()

array(['Blinkit', nan, 'BigBasket Now', 'Instamart', 'Zepto', 'blinkit'],
      dtype=object)

In [12]:
#How many unique cities are present before cleaning?

df['city'].unique()

array(['Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai', 'Delhi', 'Pune',
       nan, ' Chennai '], dtype=object)

In [13]:
#Display the frequency of every category.
df['platform'].value_counts()

platform
BigBasket Now    253
Zepto            253
Blinkit          240
Instamart        229
blinkit           20
Name: count, dtype: int64

Identify at least one suspicious data quality issues.
(1)unclean data

In [14]:
#Show only order_id, platform and order_value.
df[['order_id','platform','order_value']]

      order_id       platform  order_value
0        10001        Blinkit       667.85
1        10002        Blinkit      3724.00
2        10003            NaN       536.00
3        10004  BigBasket Now      2562.00
4        10005  BigBasket Now      4025.60
...        ...            ...          ...
1015     10016  BigBasket Now       795.60
1016     10017        Blinkit       720.00
1017     10018          Zepto      2274.75
1018     10019      Instamart      3067.20
1019     10020        Blinkit      1779.20

[1020 rows x 3 columns]

In [15]:
#Display all orders from Chennai.

df[df['city']=='Chennai']

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
2,10003,C1157,NaN,Chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,NaN,Yes,Yes,4.0,Rider E
17,10018,C1280,Zepto,Chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,NaN,Yes,Yes,3.0,Rider B
26,10027,C1042,Zepto,Chennai,Dairy,2,590,590.00,0,39.0,10,13,590.00,COD,NaN,No,No,5.0,Rider B
27,10028,C1082,NaN,Chennai,Vegetables,4,128,102.40,20,29.0,15,13,512.00,Card,Silver,No,Yes,3.0,Rider C
30,10031,C1124,Instamart,Chennai,Snacks,3,1076,807.00,25,19.0,20,34,4035.00,Wallet,Gold,No,No,3.0,Rider E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,10989,C1210,BigBasket Now,Chennai,Beverages,1,607,455.25,25,0.0,30,39,1821.00,UPI,Gold,Yes,No,2.0,Rider A
993,10994,C1146,Zepto,Chennai,Snacks,4,1057,1004.15,5,19.0,15,18,3012.45,UPI,Gold,No,No,3.0,Rider B
998,10999,C1068,NaN,Chennai,Snacks,7,746,522.20,30,0.0,15,19,1566.60,UPI,Silver,Yes,Yes,1.0,Rider D
1002,10003,C1157,NaN,Chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,NaN,Yes,Yes,4.0,Rider E
1017,10018,C1280,Zepto,Chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,NaN,Yes,Yes,3.0,Rider B

In [16]:
#Display all Blinkit orders.

df[df['platform']=='Blinkit']

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,Blinkit,Hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,Blinkit,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
6,10007,C1252,Blinkit,Bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
10,10011,C1077,Blinkit,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
16,10017,C1205,Blinkit,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,NaN,No,Yes,5.0,Rider E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,10002,C1030,Blinkit,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
1006,10007,C1252,Blinkit,Bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
1010,10011,C1077,Blinkit,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
1016,10017,C1205,Blinkit,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,NaN,No,Yes,5.0,Rider E
1019,10020,C1093,Blinkit,Bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [17]:
#Orders where delivery time is greater than promised time

df[df['delivery_time']>df['promised_time']]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,Blinkit,Hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,Blinkit,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
2,10003,C1157,NaN,Chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,NaN,Yes,Yes,4.0,Rider E
3,10004,C1299,BigBasket Now,Mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,NaN,No,No,3.0,Rider D
8,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,10015,C1132,Zepto,Pune,Beverages,6,97,67.90,30,39.0,20,30,407.40,COD,Gold,Yes,Yes,2.0,Rider D
1015,10016,C1000,BigBasket Now,Pune,Dairy,2,442,397.80,10,59.0,15,25,795.60,Wallet,NaN,Yes,No,2.0,Rider D
1016,10017,C1205,Blinkit,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,NaN,No,Yes,5.0,Rider E
1018,10019,C1166,Instamart,NaN,Snacks,3,639,511.20,20,0.0,15,28,3067.20,Wallet,NaN,No,Yes,5.0,Rider B
1019,10020,C1093,Blinkit,Bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [18]:
#Orders from Chennai OR Mumbai.

df[(df['city']=='Chennai') |(df['city']=='Mumbai')]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
2,10003,C1157,NaN,Chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,NaN,Yes,Yes,4.0,Rider E
3,10004,C1299,BigBasket Now,Mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,NaN,No,No,3.0,Rider D
8,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
10,10011,C1077,Blinkit,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
17,10018,C1280,Zepto,Chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,NaN,Yes,Yes,3.0,Rider B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,10003,C1157,NaN,Chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,NaN,Yes,Yes,4.0,Rider E
1003,10004,C1299,BigBasket Now,Mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,NaN,No,No,3.0,Rider D
1008,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
1010,10011,C1077,Blinkit,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
1017,10018,C1280,Zepto,Chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,NaN,Yes,Yes,3.0,Rider B

In [19]:
#Orders where membership is Gold.

df[df['membership']=='Gold']

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,Blinkit,Hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,Blinkit,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
4,10005,C1262,BigBasket Now,Bengaluru,Household,6,629,503.20,20,19.0,10,8,4025.60,Wallet,Gold,Yes,No,3.0,Rider C
7,10008,C1220,Instamart,Pune,fruit,6,862,689.60,20,59.0,20,19,4827.20,Card,Gold,Yes,Yes,2.0,Rider B
8,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,10008,C1220,Instamart,Pune,fruit,6,862,689.60,20,59.0,20,19,4827.20,Card,Gold,Yes,Yes,2.0,Rider B
1008,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
1010,10011,C1077,Blinkit,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
1013,10014,C1168,Zepto,Hyderabad,Household,4,496,396.80,20,19.0,30,41,2777.60,Card,Gold,No,No,NaN,Rider A
1014,10015,C1132,Zepto,Pune,Beverages,6,97,67.90,30,39.0,20,30,407.40,COD,Gold,Yes,Yes,2.0,Rider D

In [20]:
#Orders NOT from Delhi.

df[df['city']!='Delhi']

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,Blinkit,Hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,Blinkit,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
2,10003,C1157,NaN,Chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,NaN,Yes,Yes,4.0,Rider E
3,10004,C1299,BigBasket Now,Mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,NaN,No,No,3.0,Rider D
4,10005,C1262,BigBasket Now,Bengaluru,Household,6,629,503.20,20,19.0,10,8,4025.60,Wallet,Gold,Yes,No,3.0,Rider C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10016,C1000,BigBasket Now,Pune,Dairy,2,442,397.80,10,59.0,15,25,795.60,Wallet,NaN,Yes,No,2.0,Rider D
1016,10017,C1205,Blinkit,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,NaN,No,Yes,5.0,Rider E
1017,10018,C1280,Zepto,Chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,NaN,Yes,Yes,3.0,Rider B
1018,10019,C1166,Instamart,NaN,Snacks,3,639,511.20,20,0.0,15,28,3067.20,Wallet,NaN,No,Yes,5.0,Rider B
1019,10020,C1093,Blinkit,Bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [21]:
#orders with NULL ratings
df[df['rating'].isnull()]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
8,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
11,10012,C1238,BigBasket Now,Delhi,Dairy,2,1011,1011.00,0,19.0,10,20,2022.00,COD,NaN,No,No,NaN,Rider B
13,10014,C1168,Zepto,Hyderabad,Household,4,496,396.80,20,19.0,30,41,2777.60,Card,Gold,No,No,NaN,Rider A
43,10044,C1065,Zepto,Delhi,Snacks,6,626,532.10,15,29.0,10,22,2660.50,COD,NaN,No,No,NaN,Rider B
45,10046,C1124,Blinkit,Bengaluru,Dairy,2,915,869.25,5,29.0,30,31,3477.00,COD,Silver,Yes,Yes,NaN,Rider D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10996,C1240,Blinkit,Bengaluru,Personal Care,1,267,253.65,5,0.0,20,27,1268.25,UPI,Silver,Yes,Yes,NaN,Rider A
996,10997,C1133,Zepto,Pune,Household,1,1144,915.20,20,19.0,10,25,7321.60,Wallet,NaN,No,Yes,NaN,Rider C
1008,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
1011,10012,C1238,BigBasket Now,Delhi,Dairy,2,1011,1011.00,0,19.0,10,20,2022.00,COD,NaN,No,No,NaN,Rider B
1013,10014,C1168,Zepto,Hyderabad,Household,4,496,396.80,20,19.0,30,41,2777.60,Card,Gold,No,No,NaN,Rider A

In [22]:
#orders with missing cities

df[df['city'].isnull()]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
18,10019,C1166,Instamart,NaN,Snacks,3,639,511.20,20,0.0,15,28,3067.2,Wallet,NaN,No,Yes,5.0,Rider B
59,10060,C1163,BigBasket Now,NaN,Household,2,349,279.20,20,49.0,15,20,1116.8,Wallet,Gold,Yes,No,1.0,Rider A
88,10089,C1186,Zepto,NaN,Personal Care,2,178,133.50,25,59.0,10,7,934.5,UPI,Gold,Yes,Yes,1.0,Rider A
118,10119,C1141,Zepto,NaN,Personal Care,3,288,273.60,5,0.0,25,20,1641.6,Card,NaN,Yes,No,NaN,Rider E
149,10150,C1280,Instamart,NaN,Beverages,5,493,369.75,25,49.0,25,26,2958.0,Wallet,Silver,Yes,Yes,3.0,Rider B
240,10241,C1205,Blinkit,NaN,Household,6,416,353.60,15,0.0,20,36,1414.4,UPI,Silver,No,No,1.0,Rider D
297,10298,C1120,Instamart,NaN,Snacks,8,243,182.25,25,39.0,25,31,364.5,UPI,Silver,No,Yes,4.0,Rider A
317,10318,C1256,BigBasket Now,NaN,Vegetables,1,309,216.30,30,19.0,20,25,1514.1,Wallet,Silver,Yes,Yes,3.0,Rider A
331,10332,C1173,BigBasket Now,NaN,Household,4,138,96.60,30,59.0,30,39,579.6,COD,Gold,Yes,Yes,1.0,Rider C
353,10354,C1072,BigBasket Now,NaN,Personal Care,7,138,96.60,30,19.0,30,41,96.6,UPI,Silver,No,Yes,5.0,Rider D
447,10448,C1194,Blinkit,NaN,Snacks,2,424,296.80,30,49.0,25,29,2374.4,Wallet,Silver,No,No,4.0,Rider A
467,10468,C1173,BigBasket Now,NaN,Household,6,724,615.40,15,0.0,10,20,4923.2,Wallet,Gold,Yes,Yes,NaN,Rider D
496,10497,C1230,blinkit,NaN,Fruits,5,1174,939.20,20,59.0,30,36,1878.4,Card,NaN,No,Yes,1.0,Rider E
497,10498,C1210,Blinkit,NaN,Vegetables,2,619,495.20,20,59.0,30,30,1485.6,Wallet,NaN,Yes,Yes,1.0,Rider B
510,10511,C1065,Instamart,NaN,Household,3,229,160.30,30,59.0,30,29,160.3,UPI,NaN,No,No,1.0,Rider A
549,10550,C1016,Zepto,NaN,Beverages,8,1159,985.15,15,0.0,20,30,5910.9,Wallet,Silver,No,No,2.0,Rider A
627,10628,C1118,Blinkit,NaN,Vegetables,3,820,820.00,0,29.0,15,17,4920.0,UPI,Gold,Yes,Yes,3.0,Rider E
717,10718,C1022,Zepto,NaN,Dairy,7,264,224.40,15,49.0,20,27,673.2,Wallet,Gold,No,No,3.0,Rider C
729,10730,C1189,BigBasket Now,NaN,Vegetables,3,790,553.00,30,0.0,20,28,3871.0,COD,Silver,Yes,Yes,1.0,Rider B
745,10746,C1277,Blinkit,NaN,Beverages,1,862,775.80,10,19.0,15,21,5430.6,UPI,Gold,No,No,5.0,Rider A
767,10768,C1059,Instamart,NaN,Dairy,8,419,293.30,30,59.0,30,44,2346.4,Wallet,NaN,No,Yes,3.0,Rider E
784,10785,C1096,BigBasket Now,NaN,Dairy,4,468,397.80,15,0.0,30,33,795.6,Wallet,NaN,No,No,5.0,Rider C
797,10798,C1042,Zepto,NaN,fruit,7,304,243.20,20,19.0,25,22,1459.2,COD,NaN,Yes,Yes,2.0,Rider B
928,10929,C1109,Instamart,NaN,Beverages,4,1042,937.80,10,0.0,25,24,4689.0,Wallet,Gold,No,Yes,5.0,Rider C
980,10981,C1262,Blinkit,NaN,Vegetables,5,1094,765.80,30,19.0,15,10,765.8,Card,Silver,Yes,No,3.0,Rider A
1018,10019,C1166,Instamart,NaN,Snacks,3,639,511.20,20,0.0,15,28,3067.2,Wallet,NaN,No,Yes,5.0,Rider B

In [23]:
df.query("platform=='Blinkit' | platform=='Zepto'")

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,Blinkit,Hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,Blinkit,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
6,10007,C1252,Blinkit,Bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
10,10011,C1077,Blinkit,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
12,10013,C1185,Zepto,Pune,Beverages,1,1097,1097.00,0,49.0,15,26,5485.00,UPI,NaN,No,No,2.0,Rider C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013,10014,C1168,Zepto,Hyderabad,Household,4,496,396.80,20,19.0,30,41,2777.60,Card,Gold,No,No,NaN,Rider A
1014,10015,C1132,Zepto,Pune,Beverages,6,97,67.90,30,39.0,20,30,407.40,COD,Gold,Yes,Yes,2.0,Rider D
1016,10017,C1205,Blinkit,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,NaN,No,Yes,5.0,Rider E
1017,10018,C1280,Zepto,Chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,NaN,Yes,Yes,3.0,Rider B
1019,10020,C1093,Blinkit,Bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [24]:
#standardize platform names
df['platform'] = df['platform'].str.strip().str.lower()
df['city']=df['city'].str.strip().str.lower()

In [25]:
#unique city names
df['city'].unique()

array(['hyderabad', 'bengaluru', 'chennai', 'mumbai', 'delhi', 'pune',
       nan], dtype=object)

In [26]:
#fill missing value with median
df['delivery_fee'] = df['delivery_fee'].fillna(df['delivery_fee'].median())

In [27]:
#fill missing membership with None

df['membership']=df['membership'].fillna('None')

In [28]:
df.head()

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,blinkit,hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,blinkit,bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
2,10003,C1157,NaN,chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,None,Yes,Yes,4.0,Rider E
3,10004,C1299,bigbasket now,mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,None,No,No,3.0,Rider D
4,10005,C1262,bigbasket now,bengaluru,Household,6,629,503.20,20,19.0,10,8,4025.60,Wallet,Gold,Yes,No,3.0,Rider C

In [33]:
#duplicate order id's 

df[df.duplicated('order_id')]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
1000,10001,C1024,blinkit,hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1001,10002,C1030,blinkit,bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
1002,10003,C1157,NaN,chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,None,Yes,Yes,4.0,Rider E
1003,10004,C1299,bigbasket now,mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,None,No,No,3.0,Rider D
1004,10005,C1262,bigbasket now,bengaluru,Household,6,629,503.20,20,19.0,10,8,4025.60,Wallet,Gold,Yes,No,3.0,Rider C
1005,10006,C1047,instamart,delhi,Personal Care,2,1057,845.60,20,0.0,25,22,4228.00,Wallet,Silver,No,No,1.0,Rider D
1006,10007,C1252,blinkit,bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
1007,10008,C1220,instamart,pune,fruit,6,862,689.60,20,59.0,20,19,4827.20,Card,Gold,Yes,Yes,2.0,Rider B
1008,10009,C1093,instamart,mumbai,Fruits,3,517,517.00,0,39.0,25,38,3102.00,COD,Gold,Yes,No,NaN,Rider E
1009,10010,C1053,bigbasket now,pune,Snacks,1,843,716.55,15,19.0,25,32,1433.10,Card,Silver,Yes,Yes,3.0,Rider E
1010,10011,C1077,blinkit,mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
1011,10012,C1238,bigbasket now,delhi,Dairy,2,1011,1011.00,0,19.0,10,20,2022.00,COD,None,No,No,NaN,Rider B
1012,10013,C1185,zepto,pune,Beverages,1,1097,1097.00,0,49.0,15,26,5485.00,UPI,None,No,No,2.0,Rider C
1013,10014,C1168,zepto,hyderabad,Household,4,496,396.80,20,19.0,30,41,2777.60,Card,Gold,No,No,NaN,Rider A
1014,10015,C1132,zepto,pune,Beverages,6,97,67.90,30,39.0,20,30,407.40,COD,Gold,Yes,Yes,2.0,Rider D
1015,10016,C1000,bigbasket now,pune,Dairy,2,442,397.80,10,59.0,15,25,795.60,Wallet,None,Yes,No,2.0,Rider D
1016,10017,C1205,blinkit,pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,None,No,Yes,5.0,Rider E
1017,10018,C1280,zepto,chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,None,Yes,Yes,3.0,Rider B
1018,10019,C1166,instamart,NaN,Snacks,3,639,511.20,20,0.0,15,28,3067.20,Wallet,None,No,Yes,5.0,Rider B
1019,10020,C1093,blinkit,bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [39]:
#rename deliver_fee to deliver_charge

df.rename(columns={"delivery_fee":"delivery_charge"})

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_charge,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,blinkit,hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,blinkit,bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
2,10003,C1157,NaN,chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,None,Yes,Yes,4.0,Rider E
3,10004,C1299,bigbasket now,mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,None,No,No,3.0,Rider D
4,10005,C1262,bigbasket now,bengaluru,Household,6,629,503.20,20,19.0,10,8,4025.60,Wallet,Gold,Yes,No,3.0,Rider C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10016,C1000,bigbasket now,pune,Dairy,2,442,397.80,10,59.0,15,25,795.60,Wallet,None,Yes,No,2.0,Rider D
1016,10017,C1205,blinkit,pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,None,No,Yes,5.0,Rider E
1017,10018,C1280,zepto,chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,None,Yes,Yes,3.0,Rider B
1018,10019,C1166,instamart,NaN,Snacks,3,639,511.20,20,0.0,15,28,3067.20,Wallet,None,No,Yes,5.0,Rider B
1019,10020,C1093,blinkit,bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [ ]:
#sort by platform first then delivery time 

df.sort_values(['platform','delivery_time'],ascending=True)

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
675,10676,C1077,bigbasket now,bengaluru,Snacks,3,788,788.00,0,0.0,10,5,4728.00,UPI,Gold,Yes,No,2.0,Rider E
957,10958,C1079,bigbasket now,chennai,Dairy,7,1013,709.10,30,49.0,10,5,3545.50,COD,Silver,Yes,No,2.0,Rider E
113,10114,C1204,bigbasket now,hyderabad,Beverages,1,301,240.80,20,39.0,10,6,1204.00,UPI,Gold,Yes,Yes,4.0,Rider E
455,10456,C1040,bigbasket now,mumbai,Fruits,7,916,870.20,5,59.0,10,6,4351.00,COD,Silver,Yes,No,2.0,Rider D
906,10907,C1284,bigbasket now,hyderabad,Vegetables,8,985,738.75,25,29.0,10,6,5910.00,COD,None,No,Yes,5.0,Rider B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,10290,C1234,NaN,bengaluru,Beverages,1,791,791.00,0,59.0,30,28,3164.00,Wallet,None,Yes,Yes,2.0,Rider C
443,10444,C1190,NaN,bengaluru,Personal Care,1,1151,1093.45,5,59.0,15,29,2186.90,Card,Silver,Yes,No,3.0,Rider A
649,10650,C1165,NaN,hyderabad,Vegetables,5,1033,981.35,5,49.0,20,33,1962.70,Wallet,None,No,No,4.0,Rider C
211,10212,C1179,NaN,bengaluru,Beverages,7,174,121.80,30,39.0,25,41,852.60,Card,Gold,No,Yes,3.0,Rider D
158,10159,C1047,NaN,mumbai,Dairy,6,743,557.25,25,0.0,30,48,2786.25,Card,Gold,No,No,5.0,Rider D

In [45]:
#convert cities to title case

df['city'].str.title()

0       Hyderabad
1       Bengaluru
2         Chennai
3          Mumbai
4       Bengaluru
          ...
1015         Pune
1016         Pune
1017      Chennai
1018          NaN
1019    Bengaluru
Name: city, Length: 1020, dtype: object

In [48]:
#Find platforms containing 'blink'.

df[df['platform'].str.contains('blink', na=False)]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,blinkit,hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,blinkit,bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
6,10007,C1252,blinkit,bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
10,10011,C1077,blinkit,mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
16,10017,C1205,blinkit,pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,None,No,Yes,5.0,Rider E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,10002,C1030,blinkit,bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
1006,10007,C1252,blinkit,bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
1010,10011,C1077,blinkit,mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
1016,10017,C1205,blinkit,pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,None,No,Yes,5.0,Rider E
1019,10020,C1093,blinkit,bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [ ]:
#Sort by order value descending

df.sort_values('selling_price',ascending=False)

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
579,10580,C1258,Blinkit,Delhi,Personal Care,6,1180,1180.0,0,0.0,25,42,5900.0,Card,NaN,No,Yes,5.0,Rider B
676,10677,C1016,BigBasket Now,Bengaluru,Snacks,1,1173,1173.0,0,29.0,20,28,2346.0,UPI,Silver,Yes,Yes,2.0,Rider C
365,10366,C1259,Blinkit,Bengaluru,Personal Care,2,1172,1172.0,0,59.0,15,26,5860.0,UPI,Gold,Yes,No,1.0,Rider D
734,10735,C1132,Instamart,Bengaluru,Fruits,8,1166,1166.0,0,29.0,15,23,8162.0,Card,Silver,No,Yes,1.0,Rider E
955,10956,C1043,Blinkit,Bengaluru,Beverages,8,1163,1163.0,0,19.0,15,22,6978.0,COD,Gold,No,Yes,3.0,Rider B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,10282,C1205,Zepto,Bengaluru,Household,1,41,41.0,0,49.0,25,21,287.0,COD,NaN,Yes,No,1.0,Rider D
960,10961,C1265,Instamart,Pune,Vegetables,6,51,40.8,20,39.0,25,20,326.4,Card,NaN,Yes,No,5.0,Rider D
409,10410,C1190,Zepto,Pune,Snacks,2,40,36.0,10,19.0,25,27,36.0,UPI,Silver,Yes,No,NaN,Rider D
226,10227,C1091,Instamart,Pune,Beverages,5,41,32.8,20,29.0,20,16,164.0,Card,Silver,No,Yes,5.0,Rider D
831,10832,C1164,Blinkit,Mumbai,Personal Care,7,41,28.7,30,0.0,15,27,57.4,Card,NaN,No,Yes,2.0,Rider D

In [6]:
#Convert platform names to uppercase.

df['platform']=df['platform'].str.upper()

In [ ]:
#Convert cities to title case.
df['city']=df['city'].str.title()

In [13]:
#Find platforms containing 'blink'.

df[df['platform'].str.contains('blink', case=False, na=False)]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner
0,10001,C1024,BLINKIT,Hyderabad,Fruits,6,703,667.85,5,49.0,25,40,667.85,Card,Gold,Yes,No,4.0,Rider A
1,10002,C1030,BLINKIT,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
6,10007,C1252,BLINKIT,Bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
10,10011,C1077,BLINKIT,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
16,10017,C1205,BLINKIT,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,NaN,No,Yes,5.0,Rider E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001,10002,C1030,BLINKIT,Bengaluru,Personal Care,1,532,532.00,0,49.0,30,38,3724.00,UPI,Gold,Yes,Yes,3.0,Rider D
1006,10007,C1252,BLINKIT,Bengaluru,Household,5,767,728.65,5,19.0,30,28,2914.60,Wallet,Silver,No,Yes,2.0,Rider D
1010,10011,C1077,BLINKIT,Mumbai,Beverages,1,147,147.00,0,0.0,10,23,588.00,Wallet,Gold,No,No,5.0,Rider C
1016,10017,C1205,BLINKIT,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,NaN,No,Yes,5.0,Rider E
1019,10020,C1093,BLINKIT,Bengaluru,Vegetables,3,1112,889.60,20,39.0,10,19,1779.20,UPI,Silver,No,Yes,5.0,Rider A

In [ ]:
#Create high_value_order (>=1000).

df['high_value_order']=df[df['selling_price']>=1000]

In [21]:
#Create rating_category (Good/Poor).

df['rating_category']=np.where(df['rating']>=4,'Good','Poor')

In [23]:
#Replace Yes/No with True/False in coupon_used.

df['coupon_used']=np.where(df['coupon_used']=='Yes',True,False)

In [34]:
#Replace membership None with Standard.
df['membership']=df['membership'].fillna('Standard')

In [35]:
df[df['membership']=='Standard']

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner,rating_category
2,10003,C1157,NaN,Chennai,Beverages,4,335,268.00,20,29.0,10,23,536.00,UPI,Standard,True,Yes,4.0,Rider E,Good
3,10004,C1299,BigBasket Now,Mumbai,Dairy,4,915,640.50,30,19.0,20,29,2562.00,UPI,Standard,False,No,3.0,Rider D,Poor
11,10012,C1238,BigBasket Now,Delhi,Dairy,2,1011,1011.00,0,19.0,10,20,2022.00,COD,Standard,False,No,NaN,Rider B,Poor
12,10013,C1185,Zepto,Pune,Beverages,1,1097,1097.00,0,49.0,15,26,5485.00,UPI,Standard,False,No,2.0,Rider C,Poor
15,10016,C1000,BigBasket Now,Pune,Dairy,2,442,397.80,10,59.0,15,25,795.60,Wallet,Standard,True,No,2.0,Rider D,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1012,10013,C1185,Zepto,Pune,Beverages,1,1097,1097.00,0,49.0,15,26,5485.00,UPI,Standard,False,No,2.0,Rider C,Poor
1015,10016,C1000,BigBasket Now,Pune,Dairy,2,442,397.80,10,59.0,15,25,795.60,Wallet,Standard,True,No,2.0,Rider D,Poor
1016,10017,C1205,Blinkit,Pune,Vegetables,3,720,720.00,0,19.0,25,34,720.00,Card,Standard,False,Yes,5.0,Rider E,Good
1017,10018,C1280,Zepto,Chennai,Fruits,2,1011,758.25,25,49.0,20,19,2274.75,Wallet,Standard,True,Yes,3.0,Rider B,Poor
1018,10019,C1166,Instamart,NaN,Snacks,3,639,511.20,20,0.0,15,28,3067.20,Wallet,Standard,False,Yes,5.0,Rider B,Good

In [38]:
#Average order value by platform

df.groupby('platform')['selling_price'].mean().round()

platform
BigBasket Now    538.0
Blinkit          532.0
Instamart        530.0
Zepto            510.0
blinkit          586.0
Name: selling_price, dtype: float64

In [42]:
#Average delivery time by platform.

df.groupby('platform')['delivery_time'].mean().round()

platform
BigBasket Now    26.0
Blinkit          26.0
Instamart        26.0
Zepto            26.0
blinkit          29.0
Name: delivery_time, dtype: float64

In [47]:
#Count orders by city.
df.groupby('city')['order_id'].count().reset_index()

        city  order_id
0   Chennai         15
1  Bengaluru       165
2    Chennai       163
3      Delhi       138
4  Hyderabad       165
5     Mumbai       170
6       Pune       178

In [51]:
#Average order value by city.

df.groupby('city')['order_value'].mean().round().reset_index()

        city  order_value
0   Chennai        2609.0
1  Bengaluru       2371.0
2    Chennai       2303.0
3      Delhi       2287.0
4  Hyderabad       2413.0
5     Mumbai       2274.0
6       Pune       2240.0

In [53]:
#Highest order value in each city.

df.groupby('city')['order_value'].max().reset_index()

        city  order_value
0   Chennai        8624.0
1  Bengaluru       8968.0
2    Chennai       7856.0
3      Delhi       8976.0
4  Hyderabad       7833.0
5     Mumbai       8015.0
6       Pune       7866.0

In [55]:
# Total revenue by platform.

df.groupby('platform')['order_value'].sum().reset_index()

        platform  order_value
0  BigBasket Now    600635.30
1        Blinkit    569392.65
2      Instamart    555500.80
3          Zepto    552328.35
4        blinkit     42778.30

In [57]:
#Average discount by category.

df.groupby('category')['discount_percent'].mean()

category
Beverages        15.245399
Dairy            15.129870
Fruits           14.532374
Household        16.443662
Personal Care    14.292035
Snacks           14.035714
Vegetables       16.075949
fruit            12.727273
Name: discount_percent, dtype: float64

In [66]:
#. Platform with highest average rating.

df.groupby('platform')['rating'].mean().idxmax()

'Blinkit'

In [67]:
#City with highest average delivery fee

df.groupby('city')['delivery_fee'].mean().idxmax()

'Bengaluru'

In [70]:
#Average delivery time by payment mode.

df2=df.groupby('payment_mode')['delivery_time'].mean().reset_index()

In [ ]:
#top value
df2.sort_values('delivery_time',ascending=False).head(1)

  payment_mode  delivery_time
3       Wallet      27.011952

In [81]:
#Platform-wise total number of orders.

df.groupby('platform')['order_id'].count()

platform
BigBasket Now    253
Blinkit          240
Instamart        229
Zepto            253
blinkit           20
Name: order_id, dtype: int64

In [86]:
#Highest rated category.

df.groupby('category')['rating'].mean().idxmax()

'Beverages'

In [87]:
#Most common payment mode per platform.

df.groupby('platform')['payment_mode'].count()

platform
BigBasket Now    253
Blinkit          240
Instamart        229
Zepto            253
blinkit           20
Name: payment_mode, dtype: int64

In [93]:
#Find top 5 customers by spending.

df.groupby('customer_id')['order_id'].count().head(5).reset_index()

  customer_id  order_id
0       C1000         7
1       C1001         8
2       C1002         2
3       C1003         6
4       C1004         2

In [ ]:
#Which platform is fastest on average?

fastest=df.groupby('platform')['delivery_time'].mean()
fastest.sort_values(ascending=False).head(1)

#ans : BlinkIT

platform
blinkit    29.0
Name: delivery_time, dtype: float64

In [106]:
#Does coupon usage increase order value?

df.groupby('coupon_used')['order_value'].mean().reset_index()

#False Indicates that when coupon isnt used , then the order
#value cost increases!

   coupon_used  order_value
0        False  2404.124248
1         True  2233.557486

FINAL CHALLENGE

Clean the dataset from scratch without looking at notes.

In [112]:

print(df.info(),end='\n')
print("the shape is",df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1020 non-null   int64
 1   customer_id       1020 non-null   object
 2   platform          995 non-null    object
 3   city              994 non-null    object
 4   category          1020 non-null   object
 5   quantity          1020 non-null   int64
 6   mrp               1020 non-null   int64
 7   selling_price     1020 non-null   float64
 8   discount_percent  1020 non-null   int64
 9   delivery_fee      995 non-null    float64
 10  promised_time     1020 non-null   int64
 11  delivery_time     1020 non-null   int64
 12  order_value       1020 non-null   float64
 13  payment_mode      1020 non-null   object
 14  membership        1020 non-null   object
 15  coupon_used       1020 non-null   bool
 16  weekend           1020 non-null   object
 17  rating            835 non-null    float64
 18  delivery_partner  1020 non-null   object
 19  rating_category   1020 non-null   object
dtypes: bool(1), float64(4), int64(6), object(9)
memory usage: 152.5+ KB
None
the shape is (1020, 20)

Observations :
NULL values present in platform,city,category,delivery_fee,rating

In [117]:
df.groupby('city')['order_id'].count().reset_index()

        city  order_id
0   Chennai         15
1  Bengaluru       165
2    Chennai       163
3      Delhi       138
4  Hyderabad       165
5     Mumbai       170
6       Pune       178

Observations: IN consistent names : Chennai and Chennai exist twice , idk why

In [124]:
df['city']=df['city'].str.strip().str.title()

#consistent City namings

In [118]:
df.groupby('platform')['order_id'].count().reset_index()

        platform  order_id
0  BigBasket Now       253
1        Blinkit       240
2      Instamart       229
3          Zepto       253
4        blinkit        20

Observations: blinkit repeated twice. one as Blinkit , another as blinkit

In [128]:
df['platform']=df['platform'].str.strip().str.title()

#consistent platform naming

In [120]:
df[df['delivery_fee'].isnull()]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner,rating_category
99,10100,C1050,NaN,Bengaluru,Household,7,969,823.65,15,NaN,20,23,2470.95,COD,Silver,False,No,1.0,Rider E,Poor
103,10104,C1205,Zepto,Delhi,Snacks,4,583,583.00,0,NaN,15,19,1749.00,UPI,Standard,True,No,NaN,Rider E,Poor
154,10155,C1284,BigBasket Now,Pune,Dairy,1,639,575.10,10,NaN,25,36,4600.80,Wallet,Silver,False,Yes,5.0,Rider C,Good
193,10194,C1262,Instamart,Pune,Snacks,1,563,563.00,0,NaN,15,21,3378.00,UPI,Silver,False,Yes,1.0,Rider B,Poor
194,10195,C1228,Blinkit,Hyderabad,Snacks,2,561,504.90,10,NaN,15,32,4039.20,UPI,Gold,False,Yes,2.0,Rider E,Poor
255,10256,C1021,BigBasket Now,Bengaluru,Snacks,5,535,535.00,0,NaN,15,31,1605.00,COD,Gold,True,No,5.0,Rider D,Good
283,10284,C1279,Instamart,Delhi,Snacks,1,1140,1140.00,0,NaN,10,26,4560.00,UPI,Standard,False,Yes,1.0,Rider B,Poor
354,10355,C1082,Instamart,Delhi,Vegetables,5,877,789.30,10,NaN,25,38,789.30,COD,Silver,False,No,2.0,Rider E,Poor
387,10388,C1096,Zepto,Chennai,Beverages,4,299,224.25,25,NaN,10,24,448.50,Card,Standard,True,Yes,4.0,Rider E,Good
423,10424,C1243,BigBasket Now,Chennai,Vegetables,7,655,491.25,25,NaN,10,10,3438.75,Card,Silver,False,No,NaN,Rider E,Poor
431,10432,C1065,Zepto,Bengaluru,Vegetables,8,398,278.60,30,NaN,10,12,1671.60,Card,Silver,False,No,1.0,Rider B,Poor
472,10473,C1021,BigBasket Now,Pune,fruit,8,1076,1076.00,0,NaN,25,38,3228.00,Card,Standard,False,Yes,5.0,Rider D,Good
524,10525,C1260,BigBasket Now,Chennai,Household,5,976,927.20,5,NaN,25,28,3708.80,Wallet,Silver,False,Yes,NaN,Rider E,Poor
572,10573,C1114,BigBasket Now,Hyderabad,Beverages,6,883,662.25,25,NaN,20,24,4635.75,Wallet,Gold,False,Yes,4.0,Rider B,Good
612,10613,C1073,BigBasket Now,Hyderabad,Snacks,8,808,646.40,20,NaN,10,15,3878.40,Wallet,Standard,False,No,5.0,Rider C,Good
616,10617,C1078,Blinkit,Bengaluru,Personal Care,3,396,396.00,0,NaN,10,14,2772.00,COD,Gold,True,No,3.0,Rider A,Poor
633,10634,C1120,Instamart,Chennai,Beverages,2,567,538.65,5,NaN,30,31,3770.55,COD,Gold,False,No,5.0,Rider D,Good
639,10640,C1012,Blinkit,Pune,Dairy,4,325,260.00,20,NaN,15,23,2080.00,COD,Silver,True,No,3.0,Rider A,Poor
670,10671,C1168,Instamart,Delhi,Snacks,4,1029,977.55,5,NaN,30,34,7820.40,Wallet,Gold,False,Yes,NaN,Rider C,Poor
674,10675,C1195,Zepto,Chennai,Fruits,3,154,154.00,0,NaN,20,20,924.00,Wallet,Silver,False,Yes,5.0,Rider C,Good
868,10869,C1176,Zepto,Pune,Personal Care,7,1180,1003.00,15,NaN,15,26,7021.00,Card,Standard,False,No,3.0,Rider A,Poor
906,10907,C1284,BigBasket Now,Hyderabad,Vegetables,8,985,738.75,25,NaN,10,6,5910.00,COD,Standard,False,Yes,5.0,Rider B,Good
919,10920,C1007,Blinkit,Bengaluru,Vegetables,2,970,824.50,15,NaN,15,14,4122.50,UPI,Standard,True,Yes,5.0,Rider B,Good
976,10977,C1016,BigBasket Now,Delhi,Household,7,614,552.60,10,NaN,15,12,2763.00,COD,Gold,False,Yes,1.0,Rider E,Poor
990,10991,C1202,Blinkit,Pune,Fruits,3,503,452.70,10,NaN,20,27,2716.20,Card,Standard,True,No,4.0,Rider C,Good

delivery fee is given as null . we can just give it the median price,if the subscription isnt gold or silver.

In [134]:
median_price=df['delivery_fee'].median()
condition=df['delivery_fee'].isnull()|df['membership'].isin(['Gold','Silver'])
df['delivery_fee']=np.where(condition,0,median_price)

In [135]:
df[df['rating'].isnull()]

,order_id,customer_id,platform,city,category,quantity,mrp,selling_price,discount_percent,delivery_fee,promised_time,delivery_time,order_value,payment_mode,membership,coupon_used,weekend,rating,delivery_partner,rating_category
8,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,0.0,25,38,3102.00,COD,Gold,True,No,NaN,Rider E,Poor
11,10012,C1238,Bigbasket Now,Delhi,Dairy,2,1011,1011.00,0,29.0,10,20,2022.00,COD,Standard,False,No,NaN,Rider B,Poor
13,10014,C1168,Zepto,Hyderabad,Household,4,496,396.80,20,0.0,30,41,2777.60,Card,Gold,False,No,NaN,Rider A,Poor
43,10044,C1065,Zepto,Delhi,Snacks,6,626,532.10,15,29.0,10,22,2660.50,COD,Standard,False,No,NaN,Rider B,Poor
45,10046,C1124,Blinkit,Bengaluru,Dairy,2,915,869.25,5,0.0,30,31,3477.00,COD,Silver,True,Yes,NaN,Rider D,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,10996,C1240,Blinkit,Bengaluru,Personal Care,1,267,253.65,5,0.0,20,27,1268.25,UPI,Silver,True,Yes,NaN,Rider A,Poor
996,10997,C1133,Zepto,Pune,Household,1,1144,915.20,20,29.0,10,25,7321.60,Wallet,Standard,False,Yes,NaN,Rider C,Poor
1008,10009,C1093,Instamart,Mumbai,Fruits,3,517,517.00,0,0.0,25,38,3102.00,COD,Gold,True,No,NaN,Rider E,Poor
1011,10012,C1238,Bigbasket Now,Delhi,Dairy,2,1011,1011.00,0,29.0,10,20,2022.00,COD,Standard,False,No,NaN,Rider B,Poor
1013,10014,C1168,Zepto,Hyderabad,Household,4,496,396.80,20,0.0,30,41,2777.60,Card,Gold,False,No,NaN,Rider A,Poor

NULL values in ratings solution : add median value / mean value rating or fill it with 0

In [136]:
df[df['rating'].isnull()]=df['rating'].median()

C:\Users\titan\AppData\Local\Temp\ipykernel_7440\2980768113.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.0' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df[df['rating'].isnull()]=df['rating'].median()

(2) PRODUCE A CLEANED DataFrame

In [138]:
df2=df

In [ ]:
df2.groupby('platform')['order_id'].count() #its clean as it had errors in initial DF before cleaning !

platform
3.0              185
Bigbasket Now    201
Blinkit          215
Instamart        189
Zepto            206
Name: order_id, dtype: int64

3. Answer: Which platform would you recommend and why? #customer POV

whichever quick-commerce platform provides the best overall customer value based on delivery efficiency, customer satisfaction and pricing(delivery fee OR money from subscription)

least avg delivery time (25.87) - BigBasket Now
highest avg rating(3.158140) - Blinkit
highest PROFIT via delivery metrics alone - Blinkit
highest good : poor ratio 
Bigbasket 0.38222222222222224
Blinkit 0.8220338983050848
Instamart 0.7027027027027027
Zepto 0.4507042253521127-> Blinkit wins

In [ ]:
df.groupby('platform')['delivery_time'].mean().reset_index()
#checking delivery time

        platform  delivery_time
0  Bigbasket Now      25.875622
1        Blinkit      26.572093
2      Instamart      26.280423
3          Zepto      26.000000

In [ ]:
df.groupby('platform')['rating'].mean() #rating check

platform
Bigbasket Now    3.089552
Blinkit          3.158140
Instamart        2.962963
Zepto            2.805825
Name: rating, dtype: float64

In [163]:

conditions = [
    df['membership'] == 'gold',
    df['membership'] == 'silver'
]

# 2. Match them with your choices list
profit = [50, 25]

# 3. Pass both lists directly into np.select
df['profits'] = np.select(conditions, profit, default=df['delivery_fee'])

C:\Users\titan\AppData\Local\Temp\ipykernel_7440\1453946758.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['profits'] = np.select(conditions, profit, default=df['delivery_fee'])

In [167]:
df.groupby('platform')['profits'].sum()

platform
Bigbasket Now    1740.0
Blinkit          2088.0
Instamart        1624.0
Zepto            2001.0
Name: profits, dtype: float64

In [169]:
df.groupby(['platform','rating_category'])['order_id'].count()

platform       rating_category
Bigbasket Now  Good                86
               Poor               115
Blinkit        Good                97
               Poor               118
Instamart      Good                78
               Poor               111
Zepto          Good                64
               Poor               142
Name: order_id, dtype: int64

In [171]:
print('Bigbasket',86/225)
print("Blinkit",97/118)
print("Instamart",78/111)
print("Zepto",64/142)

Bigbasket 0.38222222222222224
Blinkit 0.8220338983050848
Instamart 0.7027027027027027
Zepto 0.4507042253521127

From a customer perspective, Blinkit demonstrates the strongest overall performance by combining high customer satisfaction with the highest proportion of positive experiences. Although BigBasket Now records the fastest average delivery time, Blinkit's balance across multiple customer-centric metrics makes it the strongest overall recommendation within this dataset. (same as q7)

Q4. Which city should operations improve first?

CITY THAT has low ratings , customers , lower delivery times and lower no of deliveries

In [ ]:
df.groupby('city')['order_id'].count() #delhi has least customers too!

city
Bengaluru    136
Chennai      144
Delhi        104
Hyderabad    139
Mumbai       134
Pune         154
Name: order_id, dtype: int64

In [ ]:
df.groupby('city')['rating'].mean() #delhi has the LEAST OVERALL rating followed by mum

city
Bengaluru    3.022059
Chennai      3.159722
Delhi        2.788462
Hyderabad    3.086331
Mumbai       2.888060
Pune         3.012987
Name: rating, dtype: float64

In [ ]:
df.groupby('city')['delivery_time'].mean() #mumbai takes the longest , followed by delhi

city
Bengaluru    25.904412
Chennai      25.576389
Delhi        26.894231
Hyderabad    25.395683
Mumbai       27.044776
Pune         25.889610
Name: delivery_time, dtype: float64

In [ ]:
df.groupby('city')['profits'].sum() #delhi has the least delivery-profit

city
Bengaluru    1044.0
Chennai      1247.0
Delhi         870.0
Hyderabad    1247.0
Mumbai       1189.0
Pune         1798.0
Name: profits, dtype: float64

In [ ]:
df.groupby(['city','rating_category'])['order_id'].count() /69)
print("mumbai good:bad ratio",51/83)
print("delhi good:bad ratio",35/69)
#delhi has the lowest ratio , 0.5072463768115942

city       rating_category
Bengaluru  Good               51
           Poor               85
Chennai    Good               66
           Poor               78
Delhi      Good               35
           Poor               69
Hyderabad  Good               62
           Poor               77
Mumbai     Good               51
           Poor               83
Pune       Good               60
           Poor               94
Name: order_id, dtype: int64

delhi should be a major city that improves operations first , due to lower customer satisfaction compared to others , lower ratio of good reviews:bad reviews while experiencing long delivery times

List limitations of the dataset.

synthetic-many rows had "3.0" as their platform-irregular naming/spacing